spring:
  application:
    name: movie
  data:
    mongodb:
      uri: mongodb://localhost:27017/movie_api_db
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG