spring:
  application:
    name: movie
  data:
    mongodb:
      uri: mongodb://localhost:27017/movie_api_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/movie_api_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG